import Head from 'next/head'
import styles from '../styles/Home.module.css'

interface Props {
  children: React.ReactNode
}

function Layout({ children }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web mapping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}

export default Layout